### ISSUE TITLE
Test and optimize autonomous control mode

### ISSUE THREAD

**Issue by sbrodeur** [sbrodeur/ros-icreate-bbb#10]
Make sure that autonomous control mode is still working fine:
https://github.com/sbrodeur/ros-icreate-bbb/blob/master/src/action/scripts/record/autonomous_control.py

The launch script that records the rosbag should also be adapted to the new topics:
https://github.com/sbrodeur/ros-icreate-bbb/blob/master/src/action/scripts/record/record_autonomous.launch

**Comment by sgcarrier** [comment]
Autonomous control mode works. I had to switch angles from deg to Rad because of the new messages. Also changed the launch file for the new topics.

**Comment by sbrodeur** [comment]
It seems that only the backward moving when hitting an object needs to be adjusted. The robot should move backward a fixed 3-5 cm (the minimum to clear the bumper).

**Comment by sgcarrier** [comment]
Again it was an issue of units due to new messages. Changes were done here: 28443bce8ab5f3b4439f175c2a49934f886f263c
