### ISSUE TITLE
Test rosbag recording on robot

### ISSUE THREAD

**Issue by sgcarrier** [sbrodeur/ros-icreate-bbb#11]
Verify that recording goes well, doesn't saturate and starts with appropriate key presses. Rosbags should be well labeled and allow multiple recordings without having to connect via ssh to change things.

Need to verify how long the robot can last on battery power while moving and recording.

**Comment by sgcarrier** [comment]
Recording goes well, battery sustains fine. To start recording Y+B buttons are pressed and  records for up to 10 mins or X+A is pressed, whatever happens first.  

When saved they follow the format session_X were X starts at 0 and increments each time. However, everytime  the service restart, this is reset, thus care must be taken to transfer rosbags everytime a reboot is done before recording again or else the rosbags are overwritten

**Comment by sbrodeur** [comment]
To solve the filename overwritting, I would just save the rosbag with the following format:
session_<datetime>

See the command below for an example of <datetime>:

```
date +"%Y%m%d_%H%M%S"
```

This returns something like '20160926_210957' which can be appended to the filename to indicate the date and time of the recording.

**Comment by sgcarrier** [comment]
Fixed. Output now in the format : session_[year][month][day]_[hour][min][sec].bag
