### ISSUE TITLE
Validate control range of motor speeds

### ISSUE THREAD

**Issue by sbrodeur** [sbrodeur/ros-icreate-bbb#13]
Ideally, with joystick control we should see smooth transitions in the velocities of the motors (e.g. analog mode), rather than a binary mode (e.g. null or full speed). It should look like this, and could even be smoother:

![motors](https://cloud.githubusercontent.com/assets/4322357/18977040/1338e1ac-8685-11e6-81b9-10cf1b9db6ac.png)

We just need to validate this by viewing the motor control signals in rqt, then calibrate the joystick if necessary.

**Comment by sgcarrier** [comment]
![joystick_cmd_raw](https://cloud.githubusercontent.com/assets/8992510/18999067/b386a2c8-8709-11e6-87c8-66cb4826c338.png)

It's a bit hard to tell now that joystick commands are sent asynchronously, but here is the graph. We see values are no longer binary (max, min) and can take many values in between.

**Comment by sbrodeur** [comment]
This looks nice. What about plotting the same data, but from the topic /irobot_create/motors?
With this topic, we will see exactly what the robot executed at all time.

**Comment by sgcarrier** [comment]
![joystick_motors](https://cloud.githubusercontent.com/assets/8992510/19000485/d45a09de-8710-11e6-8fc3-eb5d7fd52eac.png)

Heres the motor, for the same sequence. We see the shape is roughly the same even though motors has a synchronous output.

**Comment by sbrodeur** [comment]
This is perfect! There is no problem here.
