### ISSUE TITLE
/Imu/data values never change

### ISSUE THREAD

**Issue by sgcarrier** [sbrodeur/ros-icreate-bbb#29]
The values published in /imu/data for the orientation never change or change very slowly. My initial guess is that since /imu/data_raw and /imu/mag are on different nodes now, the Magwick filter can't find matching timestamps for both. Or, that the scale of one of the instruments has been reduced ( and thus the very slow movement).

**Comment by sbrodeur** [comment]
The problem comes from the l3gd20 gyroscope driver, where the sensitivity is not applied and thus the results are not in udps as expected:
https://github.com/sbrodeur/ros-icreate-bbb/blob/master/src/imu/drivers/l3gd20/l3gd20.c#L667

I think this was commented out to avoid overflows.

**Comment by sbrodeur** [comment]
The orientation problem is fixed with commit 8a986ce.
We only need to figure out why soft-iron correction doesn't work anymore (and was thus deactivated).

**Comment by sbrodeur** [comment]
Tested and fixed with commit 4db406b.
