### ISSUE TITLE
Update stereo camera calibration for new resolution

### ISSUE THREAD

**Issue by sbrodeur** [sbrodeur/ros-icreate-bbb#34]
Once the cameras will be fixed securely on the mounts, we should redo the calibration using the adjusted positions and the new resolution (320x240 pixels).

**Comment by sgcarrier** [comment]
See commit 92dd50e2335c02c0958e0bec93dabdfd428ffbb2 and 758b3a896d0336f19c5f66d8855bbf2872532c46 . Calibration files have been updated.
