### ISSUE TITLE
Fix soft-iron correction for magnetometer

### ISSUE THREAD

**Issue by sbrodeur** [sbrodeur/ros-icreate-bbb#36]
Soft-iron correction was disabled because it was leading to weird results after recalibration and changes in the IMU capture nodes. We should attempt to investigate this and re-enable it. This is not a priority task to do before recordings, since it can be applied offline.

**Comment by sgcarrier** [comment]
See commit 5bb15110a0ee3613574471231bb7a9ebb00d2669 . The calibration now gives the following results.
![soft_iron_corr_x_y](https://cloud.githubusercontent.com/assets/8992510/19782526/350c55f6-9c5c-11e6-89c8-f36b442bce6e.png)
![soft_iron_corr_y_z](https://cloud.githubusercontent.com/assets/8992510/19782529/36c974b4-9c5c-11e6-854c-226d8ca5e910.png)
