### ISSUE TITLE
Find relevant papers about multimodal modeling

### ISSUE THREAD

**Issue by sbrodeur** [sbrodeur/ros-icreate-bbb#4]
Compare with existing work in the literature, in terms of:
- Multimodal unsupervised  learning and feature extraction.
- Multimodal generative modeling.
- Cross-modality completion and prediction.
- Multimodal knowledge acquisition and representation.

**Comment by sgcarrier** [comment]
[Relevant_papers_0_3.pdf](https://github.com/sbrodeur/ros-icreate-bbb/files/477663/Relevant_papers_0_3.pdf)
